package mechanics;

public enum MoveType {
	NORMAL(0),
	CAPTURE(1),
	KINGSIDE_CASTLE(2),
	QUEENSIDE_CASTLE(3),
	PAWN_PROMOTION_BISHOP(4),
	PAWN_CAPTURE_PROMOTION_BISHOP(5),
	PAWN_PROMOTION_KNIGHT(6),
	PAWN_CAPTURE_PROMOTION_KNIGHT(7),
	PAWN_PROMOTION_ROOK(8),
	PAWN_CAPTURE_PROMOTION_ROOK(9),
	PAWN_PROMOTION_QUEEN(10),
	PAWN_CAPTURE_PROMOTION_QUEEN(11);
	
	private int value;
	
	private MoveType(int value) {
		this.value = value;
	}
}
